namespace Pit.JavaScript.JQuery.UI
open Pit
open Pit.Compiler
open Pit.JavaScript
open Pit.Dom
open Pit.JavaScript.JQuery

[<JsIgnore(IgnoreNamespace=true,IgnoreGetSet=true)>]
[<AstParserExtension(typeof<jQueryParser>)>]
[<Alias("$")>]
type jQueryUI(x) =
    inherit jQuery(x)

    member this.draggable() = jQuery(null)
    member this.draggable(x) = jQuery(null)
    member this.droppable() = jQuery(null)
    member this.droppable(x) = jQuery(null)
    member this.resizable() = jQuery(null)
    member this.resizable(x) = jQuery(null)
    member this.selectable() = jQuery(null)
    member this.selectable(x) = jQuery(null)
    member this.sortable() = jQuery(null)
    member this.sortable(x) = jQuery(null)
    member this.accordion() = jQuery(null)
    member this.accordion(x) = jQuery(null)
    member this.accordion(x, y) = jQuery(null)
    member this.accordion(x, y, z) = jQuery(null)
    member this.autocomplete() = jQuery(null)
    member this.autocomplete(x) = jQuery(null)
    member this.autocomplete(x, y) = jQuery(null)
    member this.autocomplete(x, y, z) = jQuery(null)
    member this.button() = jQuery(null)
    member this.button(x) = jQuery(null)
    member this.button(x, y) = jQuery(null)
    member this.button(x, y, z) = jQuery(null)
    member this.datepicker() = jQuery(null)
    member this.datepicker(x) = jQuery(null)
    member this.datepicker(x, y) = jQuery(null)
    member this.datepicker(x, y, z) = jQuery(null)
    member this.datepicker(x, y, z, a) = jQuery(null)
    member this.datepicker(x, y, z, a, b) = jQuery(null)
    member this.dialog() = jQuery(null)
    member this.dialog(x) = jQuery(null)
    member this.dialog(x, y) = jQuery(null)
    member this.dialog(x, y, z) = jQuery(null)
    member this.progressbar() = jQuery(null)
    member this.progressbar(x) = jQuery(null)
    member this.progressbar(x, y) = jQuery(null)
    member this.progressbar(x, y, z) = jQuery(null)
    member this.slider() = jQuery(null)
    member this.slider(x) = jQuery(null)
    member this.slider(x,y) = jQuery(null)
    member this.slider(x,y,z) = jQuery(null)
    member this.tabs() = jQuery(null)
    member this.tabs(x) = jQuery(null)
    member this.tabs(x, y) = jQuery(null)
    member this.tabs(x, y, z) = jQuery(null)
    member this.tabs(x, y, z, a) = jQuery(null)
    member this.toggleClass(x:string) = jQuery(null)
    member this.toggleClass(x:string, y:float) = jQuery(null)
    member this.addClass(x:string) = jQuery(null)
    member this.addClass(x:string, y:float) = jQuery(null)
    member this.removeClass() = jQuery(null)
    member this.removeClass(x:string) = jQuery(null)
    member this.removeClass(x:string, y:float) = jQuery(null)
    member this.switchClass(x:string, y:string) = jQuery(null)
    member this.switchClass(x:string, z:float) = jQuery(null)
    member this.effect(x:string) = jQuery(null)
    member this.effect(x:string, y) = jQuery(null)
    member this.effect(x:string, y, z) = jQuery(null)
    member this.effect(x:string, y, z, a) = jQuery(null)
    member this.toggle(x:string) = jQuery(null)
    member this.toggle(x:string, y) = jQuery(null)
    member this.toggle(x:string, y, z) = jQuery(null)
    member this.toggle(x:string, y, z, a) = jQuery(null)
    member this.hide(x:string) = jQuery(null)
    member this.hide(x:string, y) = jQuery(null)
    member this.hide(x:string, y, z) = jQuery(null)
    member this.hide(x:string, y, z, a) = jQuery(null)
    member this.show(x:string) = jQuery(null)
    member this.show(x:string, y) = jQuery(null)
    member this.show(x:string, y, z) = jQuery(null)
    member this.show(x:string, y, z, a) = jQuery(null)
    member this.position(x) = jQuery(null)